{"name": "Проверка ошибки при попытке авторизации пользователя c неверным логином", "status": "passed", "steps": [{"name": "POST запрос на авторизацию пользователя", "status": "passed", "parameters": [{"name": "payload_for_login_user", "value": "{'email': 'dneoyxb@yandex.ru', 'password': 'xliawouy'}"}], "start": 1719134140138, "stop": 1719134140274}], "start": 1719134140137, "stop": 1719134140275, "uuid": "5b8a1d4a-1911-47ed-b66e-1bcbf811d9e1", "historyId": "74f850f5f33bd66e941babb00811bd20", "testCaseId": "74f850f5f33bd66e941babb00811bd20", "fullName": "tests.test_2_login_user.TestLoginUser#test_login_user_with_invalid_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_2_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-5IEA5R0"}, {"name": "thread", "value": "14448-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_2_login_user"}]}